services:
  - type: web
    name: yt-downloader-api
    env: python
    region: oregon
    plan: free
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: YOUTUBE_COOKIES_B64
        sync: false
      - key: PROXY_URL
        sync: false